#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
VIDEO_DEV="${1:-/dev/video52}"
SETTINGS_FILE="${SETTINGS_FILE:-$ROOT_DIR/ui_settings.env}"
OVERRIDE_WIDTH="${WIDTH-}"
OVERRIDE_HEIGHT="${HEIGHT-}"
OVERRIDE_FPS="${FPS-}"
OVERRIDE_DETECT_INTERVAL="${DETECT_INTERVAL-}"
OVERRIDE_PIXEL_FORMAT="${PIXEL_FORMAT-}"
OVERRIDE_CAMERA_BUFFERS="${CAMERA_BUFFERS-}"
OVERRIDE_CAMERA_FPS="${CAMERA_FPS-}"
OVERRIDE_INPUT_DEV="${INPUT_DEV-}"
OVERRIDE_EXPOSURE="${EXPOSURE-}"
OVERRIDE_GAIN="${GAIN-}"
OVERRIDE_BRIGHTNESS="${BRIGHTNESS-}"
OVERRIDE_CONTRAST="${CONTRAST-}"
OVERRIDE_SATURATION="${SATURATION-}"
OVERRIDE_GAMMA="${GAMMA-}"
OVERRIDE_WHITE_BALANCE_TEMP="${WHITE_BALANCE_TEMP-}"
if [ -f "$SETTINGS_FILE" ]; then
  . "$SETTINGS_FILE"
fi
[ -n "$OVERRIDE_WIDTH" ] && WIDTH="$OVERRIDE_WIDTH"
[ -n "$OVERRIDE_HEIGHT" ] && HEIGHT="$OVERRIDE_HEIGHT"
[ -n "$OVERRIDE_FPS" ] && FPS="$OVERRIDE_FPS"
[ -n "$OVERRIDE_DETECT_INTERVAL" ] && DETECT_INTERVAL="$OVERRIDE_DETECT_INTERVAL"
[ -n "$OVERRIDE_PIXEL_FORMAT" ] && PIXEL_FORMAT="$OVERRIDE_PIXEL_FORMAT"
[ -n "$OVERRIDE_CAMERA_BUFFERS" ] && CAMERA_BUFFERS="$OVERRIDE_CAMERA_BUFFERS"
[ -n "$OVERRIDE_CAMERA_FPS" ] && CAMERA_FPS="$OVERRIDE_CAMERA_FPS"
[ -n "$OVERRIDE_INPUT_DEV" ] && INPUT_DEV="$OVERRIDE_INPUT_DEV"
[ -n "$OVERRIDE_EXPOSURE" ] && EXPOSURE="$OVERRIDE_EXPOSURE"
[ -n "$OVERRIDE_GAIN" ] && GAIN="$OVERRIDE_GAIN"
[ -n "$OVERRIDE_BRIGHTNESS" ] && BRIGHTNESS="$OVERRIDE_BRIGHTNESS"
[ -n "$OVERRIDE_CONTRAST" ] && CONTRAST="$OVERRIDE_CONTRAST"
[ -n "$OVERRIDE_SATURATION" ] && SATURATION="$OVERRIDE_SATURATION"
[ -n "$OVERRIDE_GAMMA" ] && GAMMA="$OVERRIDE_GAMMA"
[ -n "$OVERRIDE_WHITE_BALANCE_TEMP" ] && WHITE_BALANCE_TEMP="$OVERRIDE_WHITE_BALANCE_TEMP"
WIDTH="${WIDTH:-640}"
HEIGHT="${HEIGHT:-480}"
FPS="${FPS:-30}"
DETECT_INTERVAL="${DETECT_INTERVAL:-2}"
PIXEL_FORMAT="${PIXEL_FORMAT:-YUYV}"
CAMERA_BUFFERS="${CAMERA_BUFFERS:-4}"
CAMERA_FPS="${CAMERA_FPS:-30}"
INPUT_DEV="${INPUT_DEV:-/dev/input/event2}"
AUTO_EXPOSURE="${AUTO_EXPOSURE:-1}"
EXPOSURE="${EXPOSURE:-120}"
GAIN="${GAIN:-40}"
BRIGHTNESS="${BRIGHTNESS:-5}"
CONTRAST="${CONTRAST:-42}"
SATURATION="${SATURATION:-70}"
GAMMA="${GAMMA:-110}"
WHITE_BALANCE_AUTO="${WHITE_BALANCE_AUTO:-0}"
WHITE_BALANCE_TEMP="${WHITE_BALANCE_TEMP:-5000}"
MODEL="$ROOT_DIR/model/RetinaFace_mobile320_rv1126b.rknn"

cd "$ROOT_DIR"
if command -v v4l2-ctl >/dev/null 2>&1; then
  v4l2-ctl -d "$VIDEO_DEV" \
    --set-ctrl="auto_exposure=$AUTO_EXPOSURE,exposure_time_absolute=$EXPOSURE,gain=$GAIN,brightness=$BRIGHTNESS,contrast=$CONTRAST,saturation=$SATURATION,gamma=$GAMMA,white_balance_automatic=$WHITE_BALANCE_AUTO,white_balance_temperature=$WHITE_BALANCE_TEMP" \
    --set-fmt-video="width=$WIDTH,height=$HEIGHT,pixelformat=$PIXEL_FORMAT" \
    --set-parm="$CAMERA_FPS" >/dev/null 2>&1 || true
fi
exec env PIXEL_FORMAT="$PIXEL_FORMAT" CAMERA_BUFFERS="$CAMERA_BUFFERS" CAMERA_FPS="$CAMERA_FPS" INPUT_DEV="$INPUT_DEV" SETTINGS_FILE="$SETTINGS_FILE" \
  FPS="$FPS" DETECT_INTERVAL="$DETECT_INTERVAL" EXPOSURE="$EXPOSURE" GAIN="$GAIN" BRIGHTNESS="$BRIGHTNESS" \
  CONTRAST="$CONTRAST" SATURATION="$SATURATION" GAMMA="$GAMMA" WHITE_BALANCE_TEMP="$WHITE_BALANCE_TEMP" \
  ./retinaface_drm_screen "$MODEL" "$VIDEO_DEV" "$WIDTH" "$HEIGHT" "$FPS" "$DETECT_INTERVAL"
