#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
VIDEO_DEV="${1:-/dev/video52}"
SETTINGS_FILE="${SETTINGS_FILE:-$ROOT_DIR/ui_settings.env}"

OVERRIDE_WIDTH="${WIDTH-}"
OVERRIDE_HEIGHT="${HEIGHT-}"
OVERRIDE_FPS="${FPS-}"
OVERRIDE_DETECT_INTERVAL="${DETECT_INTERVAL-}"
OVERRIDE_PIXEL_FORMAT="${PIXEL_FORMAT-}"
OVERRIDE_CAMERA_BUFFERS="${CAMERA_BUFFERS-}"
OVERRIDE_CAMERA_FPS="${CAMERA_FPS-}"
OVERRIDE_WINDOW_WIDTH="${WINDOW_WIDTH-}"
OVERRIDE_WINDOW_HEIGHT="${WINDOW_HEIGHT-}"
OVERRIDE_WINDOW_X="${WINDOW_X-}"
OVERRIDE_WINDOW_Y="${WINDOW_Y-}"

if [ -f "$SETTINGS_FILE" ]; then
  . "$SETTINGS_FILE"
fi

[ -n "$OVERRIDE_WIDTH" ] && WIDTH="$OVERRIDE_WIDTH"
[ -n "$OVERRIDE_HEIGHT" ] && HEIGHT="$OVERRIDE_HEIGHT"
[ -n "$OVERRIDE_FPS" ] && FPS="$OVERRIDE_FPS"
[ -n "$OVERRIDE_DETECT_INTERVAL" ] && DETECT_INTERVAL="$OVERRIDE_DETECT_INTERVAL"
[ -n "$OVERRIDE_PIXEL_FORMAT" ] && PIXEL_FORMAT="$OVERRIDE_PIXEL_FORMAT"
[ -n "$OVERRIDE_CAMERA_BUFFERS" ] && CAMERA_BUFFERS="$OVERRIDE_CAMERA_BUFFERS"
[ -n "$OVERRIDE_CAMERA_FPS" ] && CAMERA_FPS="$OVERRIDE_CAMERA_FPS"
[ -n "$OVERRIDE_WINDOW_WIDTH" ] && WINDOW_WIDTH="$OVERRIDE_WINDOW_WIDTH"
[ -n "$OVERRIDE_WINDOW_HEIGHT" ] && WINDOW_HEIGHT="$OVERRIDE_WINDOW_HEIGHT"
[ -n "$OVERRIDE_WINDOW_X" ] && WINDOW_X="$OVERRIDE_WINDOW_X"
[ -n "$OVERRIDE_WINDOW_Y" ] && WINDOW_Y="$OVERRIDE_WINDOW_Y"

WIDTH="${WIDTH:-640}"
HEIGHT="${HEIGHT:-480}"
FPS="${FPS:-15}"
DETECT_INTERVAL="${DETECT_INTERVAL:-2}"
PIXEL_FORMAT="${PIXEL_FORMAT:-MJPG}"
CAMERA_BUFFERS="${CAMERA_BUFFERS:-4}"
CAMERA_FPS="${CAMERA_FPS:-15}"
WINDOW_WIDTH="${WINDOW_WIDTH:-512}"
WINDOW_HEIGHT="${WINDOW_HEIGHT:-600}"
WINDOW_X="${WINDOW_X:-0}"
WINDOW_Y="${WINDOW_Y:-0}"
AUTO_EXPOSURE="${AUTO_EXPOSURE:-1}"
EXPOSURE="${EXPOSURE:-120}"
GAIN="${GAIN:-40}"
BRIGHTNESS="${BRIGHTNESS:-5}"
CONTRAST="${CONTRAST:-42}"
SATURATION="${SATURATION:-70}"
GAMMA="${GAMMA:-110}"
WHITE_BALANCE_AUTO="${WHITE_BALANCE_AUTO:-0}"
WHITE_BALANCE_TEMP="${WHITE_BALANCE_TEMP:-5000}"
FACE_DB_DIR="${FACE_DB_DIR:-$ROOT_DIR/faces}"
FACE_FEATURE_MODEL="${FACE_FEATURE_MODEL:-$ROOT_DIR/model/ArcFace_112_rv1126b.rknn}"
DETECT_MODEL="$ROOT_DIR/model/RetinaFace_mobile320_rv1126b.rknn"

cd "$ROOT_DIR"
if command -v v4l2-ctl >/dev/null 2>&1; then
  v4l2-ctl -d "$VIDEO_DEV" \
    --set-ctrl="auto_exposure=$AUTO_EXPOSURE,exposure_time_absolute=$EXPOSURE,gain=$GAIN,brightness=$BRIGHTNESS,contrast=$CONTRAST,saturation=$SATURATION,gamma=$GAMMA,white_balance_automatic=$WHITE_BALANCE_AUTO,white_balance_temperature=$WHITE_BALANCE_TEMP" \
    --set-fmt-video="width=$WIDTH,height=$HEIGHT,pixelformat=$PIXEL_FORMAT" \
    --set-parm="$CAMERA_FPS" >/dev/null 2>&1 || true
fi

exec env DISPLAY="${DISPLAY:-:0}" PIXEL_FORMAT="$PIXEL_FORMAT" CAMERA_BUFFERS="$CAMERA_BUFFERS" \
  WINDOW_X="$WINDOW_X" WINDOW_Y="$WINDOW_Y" \
  FACE_RECOG_THRESHOLD="${FACE_RECOG_THRESHOLD:-0.79}" FACE_RECOG_MARGIN="${FACE_RECOG_MARGIN:-0.08}" \
  FACE_RECOG_CENTROID_THRESHOLD="${FACE_RECOG_CENTROID_THRESHOLD:-0.66}" \
  FACE_RECOG_SAMPLE_VOTE_THRESHOLD="${FACE_RECOG_SAMPLE_VOTE_THRESHOLD:-0.72}" \
  FACE_RECOG_MIN_SAMPLE_VOTES="${FACE_RECOG_MIN_SAMPLE_VOTES:-2}" \
  FACE_RECOG_MIN_SIZE="${FACE_RECOG_MIN_SIZE:-70}" FACE_RECOG_INTERVAL="${FACE_RECOG_INTERVAL:-3}" \
  FACE_RECOG_STABLE_HITS="${FACE_RECOG_STABLE_HITS:-2}" FACE_RECOG_HOLD_FRAMES="${FACE_RECOG_HOLD_FRAMES:-8}" \
  STRANGER_ALERT_SECONDS="${STRANGER_ALERT_SECONDS:-10}" \
  STRANGER_ALERT_INTERVAL_SECONDS="${STRANGER_ALERT_INTERVAL_SECONDS:-10}" \
  STRANGER_ENTRY_CONFIRM_SECONDS="${STRANGER_ENTRY_CONFIRM_SECONDS:-1}" \
  SECURITY_STATUS_FILE="${SECURITY_STATUS_FILE:-/tmp/face_ai_security_status.json}" \
  SECURITY_EVENTS_FILE="${SECURITY_EVENTS_FILE:-/tmp/face_ai_security_events.jsonl}" \
  SECURITY_CONFIG_FILE="${SECURITY_CONFIG_FILE:-/userdata/llm/ui/security_config.json}" \
  ./retinaface_x11_recognize "$DETECT_MODEL" "$FACE_FEATURE_MODEL" "$VIDEO_DEV" "$FACE_DB_DIR" \
  "$WIDTH" "$HEIGHT" "$FPS" "$WINDOW_WIDTH" "$WINDOW_HEIGHT" "$DETECT_INTERVAL"
